### ISSUE TITLE
Stuck syncing at block 468043

### ISSUE THREAD

**Issue by Scalextrix** [mannacurrency/manna#1]
I had Manna-Qt (0.8.2) installed and as part of the switch to new addressing I compiled Manna (0.8.3), I left the blockchain files in tact but removed wallet.dat and on starting the new version it began to re-index.  However at height 468043 the re-index stopped.

Debug reads:

> 1526543550 ProcessBlock: ACCEPTED

> 1526543550 InvalidChainFound: invalid

> block=00000000000046d104179c6d34c4adc0d1cbdf75d381364000657df44200e09d
  
> height=565703	log2_trust=67.959529	date=2016-10-30 02:13:03

> 1526543550 InvalidChainFound:	current

> best=0000000000001a6d3833d129005b0193aa022ac1aaf2915924ee5c75360ad445

> height=468043	log2_trust=67.706209	date=2016-07-19 22:46:37

**Comment by Scalextrix** [comment]
Deleting the block-chain files and syncing from zero fixed the issue

**Comment by goodthebest** [comment]
@Scalextrix Do you have any active node running for Manna? I need to add a node to sync the wallet.
